// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPKtuMI-qV7SZrxu0SJGtdfFdLIPLCpA',
    appId: '1:874143958246:web:fe086816a4fb2cf952a727',
    messagingSenderId: '874143958246',
    projectId: 'hotel-d90ef',
    authDomain: 'hotel-d90ef.firebaseapp.com',
    storageBucket: 'hotel-d90ef.firebasestorage.app',
    measurementId: 'G-CYYYNNLJQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlr9yHuE9QztQT3106f43qABHYxkJEoh0',
    appId: '1:874143958246:android:9a8b3eaaa396097b52a727',
    messagingSenderId: '874143958246',
    projectId: 'hotel-d90ef',
    storageBucket: 'hotel-d90ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDGXs0hVqH2xBTMGSkeoqNvQOqoTPGQg',
    appId: '1:874143958246:ios:6f15332fd502d0e452a727',
    messagingSenderId: '874143958246',
    projectId: 'hotel-d90ef',
    storageBucket: 'hotel-d90ef.firebasestorage.app',
    iosBundleId: 'com.example.hotelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDGXs0hVqH2xBTMGSkeoqNvQOqoTPGQg',
    appId: '1:874143958246:ios:6f15332fd502d0e452a727',
    messagingSenderId: '874143958246',
    projectId: 'hotel-d90ef',
    storageBucket: 'hotel-d90ef.firebasestorage.app',
    iosBundleId: 'com.example.hotelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGPKtuMI-qV7SZrxu0SJGtdfFdLIPLCpA',
    appId: '1:874143958246:web:1cded26a9909899e52a727',
    messagingSenderId: '874143958246',
    projectId: 'hotel-d90ef',
    authDomain: 'hotel-d90ef.firebaseapp.com',
    storageBucket: 'hotel-d90ef.firebasestorage.app',
    measurementId: 'G-3E1NFXNMB9',
  );
}
